name: publish

on:
  push:
    branches: 
      - ci-cd
    paths-ignore:
      - '**.md'
      - 'LICENSE'
      - 'CITATION'

jobs:

  publish:
    name: "publish" 
    runs-on: ubuntu-latest
    steps:
    - name: Login to Docker Hub
      run: |
          echo "::add-mask::${{secrets.DOCKER_HUB_PSK}}"
    - uses: docker/login-action@v1
      with:
        username: ${{secrets.DOCKER_HUB_USERNAME}}
        password: ${{secrets.DOCKER_HUB_PSK}}
    - uses: actions/checkout@v2      
    - uses: akashdhruv/Maple/.github/actions/maple@main
    - name: Publish Amrex Image
      run: |
          maple image build amrex --base=${{secrets.DOCKER_HUB_USERNAME}}/bittree:latest --as-root
          maple container publish --image=amrex
          maple push amrex ${{secrets.DOCKER_HUB_USERNAME}}/amrex:latest
